export const INITIAL_DRUPAL_DATA_FETCHED = 'INITIAL_DRUPAL_DATA_FETCHED';
export const INITIAL_RAILS_DATA_FETCHED = 'INITIAL_RAILS_DATA_FETCHED';

export const INDIVIDUAL_MEDIA_ARCHIVE = 'INDIVIDUAL_MEDIA_ARCHIVE';
export const BIBLE_READINGS = 'BIBLE_READINGS';
export const FILTER_SELECTED = 'FILTER_SELECTED';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const BRAINTREE_CLIENT_TOKEN = 'BRAINTREE_CLIENT_TOKEN';
export const DONATION_ID = 'DONATION_ID';
export const LOGOUT = 'LOGOUT';

export const USER_BIBLE_READINGS = 'USER_BIBLE_READINGS';
export const USER_BIBLE_READING = 'USER_BIBLE_READING';
export const USER_BIBLE_READING_STATUS_UPDATING = 'USER_BIBLE_READING_STATUS_UPDATING';
export const SET_CURRENT_DAY = 'SET_CURRENT_DAY';

export const EVENTS_FETCHED = 'EVENTS_FETCHED';
export const EVENTS_FETCHING = 'EVENTS_FETCHING';
export const SET_CURRENT_MONTH = 'SET_CURRENT_MONTH';
export const SET_CURRENT_VIDEO = 'SET_CURRENT_VIDEO';
export const SET_SCREEN_MODE = 'SET_SCREEN_MODE';

export const SET_FORM_DATA = 'SET_FORM_DATA';
export const SET_FORM_VALIDITY = 'SET_FORM_VALIDITY';
export const SET_FORM_SAVING = 'SET_FORM_SAVING';
export const RESET_FORM_DATA = 'RESET_FORM_DATA';

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const INITIAL_PUSH_NOTIFICATION = 'INITIAL_PUSH_NOTIFICATION';
export const PUSH_NOTIFICATION_ALERT = 'PUSH_NOTIFICATION_ALERT';

export const SET_CURRENT_RESOURCE_ID = 'SET_CURRENT_RESOURCE_ID';
export const SET_RESOURCE_CATEGORY_ID = 'SET_RESOURCE_CATEGORY_ID';
export const SET_CURRENT_GIVING_CATEGORY_ID = 'SET_CURRENT_GIVING_CATEGORY_ID';
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';

export const GET_PASSWORD_RESET_TOKEN = 'GET_PASSWORD_RESET_TOKEN';
export const VALIDATE_PASSWORD_RESET_TOKEN = 'VALIDATE_PASSWORD_RESET_TOKEN';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const SET_AMOUNT_FOR_GIVING_CATEGORY = 'SET_AMOUNT_FOR_GIVING_CATEGORY';
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const APP_INITIALIZED = 'APP_INITIALIZED';
export const APP_ACTIVE = 'APP_ACTIVE';
export const SET_NETWORK_STATE = 'SET_NETWORK_STATE';

export const SET_GUEST_MODE = 'SET_GUEST_MODE';
export const EXIT_GUEST_MODE = 'EXIT_GUEST_MODE';
